---

#-  name: Get status of etc repo
#   command: hg --cwd /etc st
#   register: hg_st
#   check_mode: no
#   changed_when: no
#   become: true

- name: Commit etc repo if needed
  command: hg --cwd /etc com -u '{{ hgusers[hguser] }}' -Am '{{ comment }}'
  become: true
  register: out
  changed_when: out.stdout is defined and out.stdout != "nothing changed"
  failed_when: false

- name: fichiers commités
  debug: var=out.stdout_lines
  when: out.stdout_lines is defined and out.stdout_lines|length > 0 and out.stdout != "nothing changed"

#pas de push, serveur de centralisation à remettre en oeuvre
#- name: Push if requested
#  delegate_to: localhost
#  register: push
#  failed_when: push.rc > 1
#  changed_when: False
#  when: push|bool
#  command: ssh -A {{ ansible_ssh_host|default(inventory_hostname) }} -l root hg --cwd /etc push

#- name: Get last commit id
#  command: hg --cwd /etc id
#  register: id
#  check_mode: no
#  changed_when: False#

#- name: Print last commit id
#  debug: { msg: '{{ id.stdout.split()[0] }}' }
